name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://transfer.sh/(RECOMMENDED)'

env:
  RECOVERY_URL: https://oshi.at/Rpjg

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Fetch image from URL
      run: |
        echo "Downloading from: ${{ github.event.inputs.RECOVERY_URL }}"
        wget -O recovery.img "${{ github.event.inputs.RECOVERY_URL }}" || { echo "Download failed!"; exit 1; }

    - name: Patch Process-1
      run: |
        chmod a+x script1.sh magiskboot
        ./script1.sh

    - name: Patch Process-2
      run: |
        chmod a+x script2.sh
        ./script2.sh
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
        mkdir -p output
        mv recovery-patched.img output/recovery.img
        tar cvf output/fastbootd-recovery.tar -C output recovery.img
        md5sum output/fastbootd-recovery.tar >> output/fastbootd-recovery.tar
        mv output/fastbootd-recovery.tar output/fastbootd-recovery.tar.md5

    - name: Upload Recovery Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Patched-Recovery
        path: output/*.md5

